import {
  mdiAccessPoint,
  mdiAccount,
  mdiAccountGroup,
  mdiArrowLeft,
  mdiAsterisk,
  mdiBellOutline,
  mdiBriefcase,
  mdiBriefcaseVariant,
  mdiCached,
  mdiCalendarCheckOutline,
  mdiCalendarFilter,
  mdiCalendarStart,
  mdiCancel,
  mdiCardAccountMailOutline,
  mdiChartBoxOutline,
  mdiCheck,
  mdiCheckBold,
  mdiCheckCircle,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCloseBox,
  mdiCloseThick,
  mdiCogBox,
  mdiCommentMultiple,
  mdiCommentMultipleOutline,
  mdiDeleteOutline,
  mdiEmail,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileChartOutline,
  mdiFileDocument,
  mdiFileDocumentOutline,
  mdiFileExcelOutline,
  mdiFileMultiple,
  mdiFilePdfBox,
  mdiFilePowerpointOutline,
  mdiFileWordOutline,
  mdiFilter,
  mdiFilterMenu,
  mdiFolderOpen,
  mdiFormatAnnotationPlus,
  mdiFormatListText,
  mdiForum,
  mdiGlassStange,
  mdiHome,
  mdiImageBrokenVariant,
  mdiLoading,
  mdiLock,
  mdiMagnify,
  mdiMenu,
  mdiMessageText,
  mdiMinusBox,
  mdiNoteMultiple,
  mdiNoteMultipleOutline,
  mdiNumeric,
  mdiPalette,
  mdiPanoramaOutline,
  mdiPlus,
  mdiRadioboxMarked,
  mdiRefresh,
  mdiReorderHorizontal,
  mdiRobot,
  mdiServer,
  mdiStore,
  mdiSwapVerticalBold,
  mdiTable,
  mdiViewList,
} from '@mdi/js'

/**
 * SVG paths for Material Design Icons used throughout eBoard.
 * Keys accept the concise eBoard name (for example, `home`).
 */
export const eboardMdiIcons = {
  'access-point': mdiAccessPoint,
  'account': mdiAccount,
  'account-group': mdiAccountGroup,
  'arrow-left': mdiArrowLeft,
  'asterisk': mdiAsterisk,
  'bell-outline': mdiBellOutline,
  'briefcase': mdiBriefcase,
  'briefcase-variant': mdiBriefcaseVariant,
  'cached': mdiCached,
  'calendar-check-outline': mdiCalendarCheckOutline,
  'calendar-filter': mdiCalendarFilter,
  'calendar-start': mdiCalendarStart,
  'cancel': mdiCancel,
  'card-account-mail-outline': mdiCardAccountMailOutline,
  'chart-box-outline': mdiChartBoxOutline,
  'check': mdiCheck,
  'check-bold': mdiCheckBold,
  'check-circle': mdiCheckCircle,
  'checkbox-blank-outline': mdiCheckboxBlankOutline,
  'checkbox-marked': mdiCheckboxMarked,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  'close': mdiClose,
  'close-box': mdiCloseBox,
  'close-thick': mdiCloseThick,
  'cog-box': mdiCogBox,
  'comment-multiple': mdiCommentMultiple,
  'comment-multiple-outline': mdiCommentMultipleOutline,
  'delete-outline': mdiDeleteOutline,
  'email': mdiEmail,
  'eye-off-outline': mdiEyeOffOutline,
  'eye-outline': mdiEyeOutline,
  'file-chart-outline': mdiFileChartOutline,
  'file-document': mdiFileDocument,
  'file-document-outline': mdiFileDocumentOutline,
  'file-excel-outline': mdiFileExcelOutline,
  'file-multiple': mdiFileMultiple,
  'file-pdf-box': mdiFilePdfBox,
  'file-powerpoint-outline': mdiFilePowerpointOutline,
  'file-word-outline': mdiFileWordOutline,
  'filter': mdiFilter,
  'filter-menu': mdiFilterMenu,
  'folder-open': mdiFolderOpen,
  'format-annotation-plus': mdiFormatAnnotationPlus,
  'format-list-text': mdiFormatListText,
  'forum': mdiForum,
  'glass-stange': mdiGlassStange,
  'home': mdiHome,
  'image-broken-variant': mdiImageBrokenVariant,
  'loading': mdiLoading,
  'lock': mdiLock,
  'magnify': mdiMagnify,
  'menu': mdiMenu,
  'message-text': mdiMessageText,
  'minus-box': mdiMinusBox,
  'note-multiple': mdiNoteMultiple,
  'note-multiple-outline': mdiNoteMultipleOutline,
  'numeric': mdiNumeric,
  'palette': mdiPalette,
  'panorama-outline': mdiPanoramaOutline,
  'plus': mdiPlus,
  'radiobox-marked': mdiRadioboxMarked,
  'refresh': mdiRefresh,
  'reorder-horizontal': mdiReorderHorizontal,
  'robot': mdiRobot,
  'server': mdiServer,
  'store': mdiStore,
  'swap-vertical-bold': mdiSwapVerticalBold,
  'table': mdiTable,
  'view-list': mdiViewList,
} as const

export type EboardMdiIconName = keyof typeof eboardMdiIcons
